application:
  name: ${rootProject.name}
  version: ${version}
logging:
  level:
    root: info
    io.github.syakuis: trace
    org.springframework.web: info
server:
  port: 8080
spring:
  main:
    banner-mode: console